FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY ["PassPoint.Api/PassPoint.Api.csproj", "PassPoint.Api/"]
RUN dotnet restore "PassPoint.Api/PassPoint.Api.csproj"

COPY . .
WORKDIR "/src/PassPoint.Api"
RUN dotnet publish "PassPoint.Api.csproj" -c Release -o /app/publish --no-restore /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
WORKDIR /app

ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080

COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "PassPoint.Api.dll"]